### ISSUE TITLE
Address Security Vulnerability Affecting 6.3.5-6.4.10

### ISSUE THREAD

**Issue by brodkin** [nkatsaros/docker-atlassian-jira#1]
According to Atlassian:

> a critical security vulnerability that exists in JIRA from version 6.3.5, up to but not including 6.4.11

More [detailed information](https://confluence.atlassian.com/jira/jira-and-hipchat-for-jira-plugin-security-advisory-2015-08-26-776650785.html) is available at Atlassian's Website.

**Comment by nkatsaros** [comment]
I updated to 6.4.11. Unfortunately, they haven't issued a patch for 6.3, so users of 6.3 will need to update the Hipchat plugin manually.

**Comment by brodkin** [comment]
Thanks!
