### ISSUE TITLE
Upgrade to JVM to 1.8

### ISSUE THREAD

**Issue by brodkin** [nkatsaros/docker-atlassian-jira#2]
Hi Nicholas,

With the release of JIRA Software (v7) a newer JVM is required. Version 1.7.0_79 is currently installed. I'll send a PR if I can.

**Comment by nkatsaros** [comment]
Sure, go ahead. I'm currently on vacation right now so I don't know if I'll
get to it immediately, but I saw that 7 was released and I was planning on
fixing it.

**Comment by brodkin** [comment]
Okay, I started diving into it, but I need your guidance. Debian jessie does not currently have openjdk 8 available via Aptitude. This can be fixed by allowing unrestricted access to the unstable repository, but preferring stable versions. I'm not sure if you want to do that. Thoughts?

**Comment by nkatsaros** [comment]
Take a look at my atlassian bitbucket repo
https://github.com/nkatsaros/docker-atlassian-bitbucket/blob/master/Dockerfile.tmpl
where I had to solve the same issue. I ended up using jessie-backports as a
base, which I didn't really want to do. The other alternative is to just
use the Oracle JVM.

**Comment by brodkin** [comment]
Oh, great. I must have been reading old information. The docs I read said that v8 isn't available in backports, but that was out of date.

**Comment by brodkin** [comment]
FWIW The technique you used in the other repo seems to not work here. I've reached out to Atlassian for advice, but when openjdk 8 is installed an error is returned during startup:

`Wrong JVM version! You are running with .. but JIRA requires at least 1.8 to run.`

I'll look at alternative methods to see if I have better success.

**Comment by nkatsaros** [comment]
The docs at
https://confluence.atlassian.com/adminjiraserver070/supported-platforms-749382629.html
say that they only support the Oracle 1.8 JDK/JRE now. I think my
confluence package uses installs that, so you can look there for an
example. I don't really want to build on top of the oracle jdk base image.

**Comment by brodkin** [comment]
YKW? I totally read that document and didn't notice that Open JDK is
unlisted.

In any event this will need to be a new repo since the feeds used by the
current repo provide JIRA Core and JIRA Software is being maintained
separately in its own feed. Are you interested in maintaining a JIRA
Software repo?
On Sun, Oct 11, 2015 at 20:13 Nicholas Katsaros notifications@github.com
wrote:

> The docs at
> 
> https://confluence.atlassian.com/adminjiraserver070/supported-platforms-749382629.html
> say that they only support the Oracle 1.8 JDK/JRE now. I think my
> confluence package uses installs that, so you can look there for an
> example. I don't really want to build on top of the oracle jdk base image.
> 
> On Monday, 12 October 2015, Ryan Brodkin notifications@github.com wrote:
> 
> > FWIW The technique you used in the other repo seems to not work here.
> > I've
> > reached out to Atlassian for advice, but when openjdk 8 is installed an
> > error is returned during startup:
> > 
> > Wrong JVM version! You are running with .. but JIRA requires at least 1.8
> > to run.
> > 
> > I'll look at alternative methods to see if I have better success.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/nkatsaros/docker-atlassian-jira/issues/2#issuecomment-147271660
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nkatsaros/docker-atlassian-jira/issues/2#issuecomment-147281185
> .

## 

Brodkin CyberArts
http://brodkinca.com | 310.220.0590
DESIGN. DEVELOPMENT. CONSULTING.

Information contained in this email or any attachment may be of 
a confidential nature which should not be disclosed to, copied or used by 
anyone other than the addressee. If you receive this email in error, please 
delete the email from your computer. Do not post anything in this email to 
any online forum without express permission of the sender. No pixels were 
harmed in the making of this disclaimer.

**Comment by nkatsaros** [comment]
As the new releases deviate from the old ones I've done two different
things. In the case of stash/bitbucket I made a new repository. In the case
of JDK 1.7/1.8 compatibility I used branches. Since there are two feeds now
I'm not really sure what I'll do, but keeping Core as master and Software
as a branch might be fine.

**Comment by brodkin** [comment]
FWIW there is a third downloadable edition for service desk with its own feed. I can also submit a PR for that, but I'm not certain you're interested.
